---
abstract: 'Various scripts to manage Koha instances'
author:
  - 'Frédéric Demians <f.demians@tamil.fr>'
build_requires:
  File::Find: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Koha-Contrib-Tamil
requires:
  AnyEvent: 0
  AnyEvent::Processor: 0
  AnyEvent::Processor::Conversion: 0
  Business::ISBN: 0
  Carp: 0
  DBI: 0
  DateTime: 0
  Fatal: 0
  File::Path: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::File: 0
  Koha::Contrib::Tamil::RecordWriter::File: 0
  List::Util: 0
  Locale::TextDomain: 0
  MARC::Batch: 0
  MARC::File::XML: 0
  MARC::Record: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt: 0
  MooseX::LogDispatch: 0
  MooseX::RW::Reader: 0
  MooseX::RW::Writer::File: 0
  Pod::Usage: 0
  XML::Simple: 0
  XML::Writer: 0
  YAML: 0
  YAML::Syck: 0
  ZOOM: 0
  diagnostics: 0
  feature: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  repository: http://git.tamil.fr/git/Koha-Contrib-Tamil
version: 0.020
