---
abstract: 'Synchronise un catalogue Koha avec Mir@bel'
author:
  - 'Frédéric Demians <f.demians@tamil.fr>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: koha-mirabel
requires:
  C4::Biblio: '0'
  DateTime: '0'
  FindBin: '0'
  Getopt::Long: '0'
  LWP::Simple: '0'
  List::Util: '0'
  MARC::Moose::Field::Std: '0'
  MARC::Moose::Record: '0'
  Modern::Perl: '0'
  Moose: '0'
  XML::Simple: '0'
  YAML: '0'
  utf8: '0'
version: 0.0.1
